table aliases  file:/etc/mail/aliases
table virtuals { "@xn--dckjf5dtd7c1a8tzcde.xn--w8je.xn--tckwe" = "_mailproc" }

listen on socket
listen on lo0
listen on egress port 25 hostname xn--dckjf5dtd7c1a8tzcde.xn--w8je.xn--tckwe

action "local_mail" mbox alias <aliases>
action "lists_mda"  mda "/home/scripts/mailproc/processor.py" user _mailproc virtual <virtuals>
action "outbound"   relay

match from any   for domain "xn--dckjf5dtd7c1a8tzcde.xn--w8je.xn--tckwe" action "lists_mda"
match from local for local              action "local_mail"
match from local for any               action "outbound"
