#!/bin/ksh

daemon="/usr/local/bin/python3"
daemon_flags="/home/scripts/mirrors-svc/server.py"
daemon_user=_mirrorssvc
daemon_logger=daemon.info
rc_bg=YES
rc_reload=NO

. /etc/rc.d/rc.subr

rc_cmd $1
