# $OpenBSD: pf.conf

set skip on lo

# tables
table <bruteforce> persist
table <ddos> persist

# default
block return
pass

# block bad actors
block in quick from <ddos>
block in quick from <bruteforce>

# X11
block return in on ! lo0 proto tcp to port 6000:6010

# pbuild
block return out log proto {tcp udp} user _pbuild

# SSH - rate limit bruteforce
pass in on egress proto tcp to port 22 keep state \
    (max-src-conn 5, max-src-conn-rate 3/10, \
     overload <bruteforce> flush global)

# HTTP/HTTPS - rate limit ddos
pass in on egress proto tcp to port { 80 443 } synproxy state \
    (max-src-conn 100, max-src-conn-rate 15/5, \
     overload <ddos> flush global)
