Section "InputClass"
    Identifier      "wsmouse"
    MatchDevicePath "/dev/wsmouse"
    Driver          "ws"
    Option          "EmulateWheel"        "true"
    Option          "EmulateWheelButton"  "2"
    Option          "EmulateWheelInertia" "10"
    Option          "YAxisMapping"        "4 5"
    Option          "XAxisMapping"        "6 7"
EndSection
