server "default" {
    listen on * port 80
    root "/htdocs"

    location "/.well-known/acme-challenge/*" {
        root "/acme"
        request strip 2
    }

    location * {
        block return 301 "https://xn--dckjf5dtd7c1a8tzcde.xn--w8je.xn--tckwe$REQUEST_URI"
    }
}

server "default" {
    listen on * tls port 443
    root "/htdocs"

    tls {
        certificate "/etc/ssl/openbsd-kiku.crt"
        key "/etc/ssl/private/openbsd-kiku.key"
    }
}
