authority letsencrypt {
    api url "https://acme-v02.api.letsencrypt.org/directory"
    account key "/etc/ssl/private/letsencrypt.key"
}

domain openbsd-kiku {
    domain name "xn--dckjf5dtd7c1a8tzcde.xn--w8je.xn--tckwe"
    domain key "/etc/ssl/private/openbsd-kiku.key"
    domain certificate "/etc/ssl/openbsd-kiku.crt"
    domain chain certificate "/etc/ssl/openbsd-kiku-chain.crt"
    sign with letsencrypt
}
